# Generated by Django 5.2.8 on 2025-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_species_chromosome'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='protein_sequence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
